### ISSUE TITLE
Running on Azure DevOps (ADO) Ubuntu agents gives the following error 'node --no-warnings: No such file or directory'

### ISSUE THREAD

**Issue by richard-sistern** [kontent-ai/data-ops#131]
### Brief bug description

Hi, this may be a bit of an edge case...  When running on Azure DevOps Ubuntu agents, the following npx command:

`npx @kontent-ai/data-ops@2.3.4`

Errors with:

```
/usr/bin/env: ‘node --no-warnings’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

I believe this to be caused by https://github.com/kontent-ai/data-ops/blob/d02586494e68d51d119e53c53760345a2aa0caae/src/index.ts#L1

### Repro steps

Not tested on standard Ubuntu, if you have ado the following pipeline recreates the error:
```yaml
trigger: none
pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: backup
    displayName: Backup Kontent.ai
    jobs:
    - job: 
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '22.14.0'  # LTS
          displayName: 'Install Node.js'
        - script: |
            npx @kontent-ai/data-ops@latest
```

### Expected behavior

The cli help is displayed.

### Test environment

 - Platform/OS: [ubuntu-22.04 & ubuntu-24.04 agents]
 - Version [node: 22.14.0,data-ops: 2.3.4]

### Additional context

This works fine on Windows ADO agents and Windows desktop.  

Looking [at the docs](https://www.gnu.org/software/coreutils/manual/html_node/env-invocation.html#g_t_002dS_002f_002d_002dsplit_002dstring-usage-in-scripts), I think this might work:

```
#!/usr/bin/env -S node --no-warnings
```

May cause [issues on older versions of Ubuntu](https://unix.stackexchange.com/a/477651) though.  Please let me know if I can help with testing.
